site_name: lua-Spore
site_description: a generic ReST client
site_author: Fran√ßois Perrad
repo_url: https://framagit.org/fperrad/lua-Spore
pages:
- Home: index.md
- API:
  - Spore: spore.md
  - Spore.Middleware: middleware.md
  - Spore.GoogleDiscovery: discovery.md
  - Spore.Swagger: swagger.md
  - Spore.WADL: wadl.md
theme: mkdocs
copyright: Copyright &copy; 2010-2018 Fran&ccedil;ois Perrad
